### ISSUE TITLE
Will not compile on OS X 10.13

### ISSUE THREAD

**Issue by marcotama** [anntzer/mplcairo#14]
I am trying to installing mplcairo via

```
brew install pkg-config libffi cairo py3cairo
LIBFFI_PC_PATH=`locate libffi.pc | grep usr | head -n 1`
LIBFFI_PKGCONFIG_PATH=`dirname "$LIBFFI_PC_PATH"`
export PKG_CONFIG_PATH="$LIBFFI_PKGCONFIG_PATH"
pip install mplcairo
```

but I get

```
src/_mplcairo.cpp:42:3: error: call to unavailable function 'visit': introduced in macOS 10.14
      std::visit([&](auto const& aa) -> void {
      ^~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/include/c++/v1/variant:1524:26: note: candidate function [with _Visitor = (lambda at src/_mplcairo.cpp:42:14), _Vs = <const std::__1::variant<_cairo_antialias, bool> &>] has been explicitly made unavailable
    constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
```

I am actually running OS X 10.13. Is it possible to install mplcairo on this version?
Just in case, I am on Python 3.7.

**Comment by anntzer** [comment]
Are you running llvm 8?  I realized very recently that for some reason I don't understand yet, you must apparently llvm 7 on macOS10.13 (see https://github.com/anntzer/mplcairo/commit/d2ca6c134398b20c7fa961e35871a256b264b879 for that fix to the CI build).  Can you give that a try?
More insight on what changed with llvm 8 would be welcome too (as I don't actually develop on that platform, so all I can do is make sure CI passes...).

**Comment by marcotama** [comment]
`llvm-gcc -v` returns

```
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I am not sure how to change the LLVM version in a safe way (I do not want to disrupt my otherwise working environment). Can you assist on this?

**Comment by anntzer** [comment]
`brew install <some specific llvm version>` does *not* make that llvm the compiler by default; it prints out some messages explaining the environment variables that need to be additionally set to use that compiler ($PATH, $CPPFLAGS, $LDFLAGS -- see just below the patch linked above) so your environment will be fine (just set these environment variables before running setup.py).

**Comment by marcotama** [comment]
Using LLVM7 works.

Full installation via:
```
# Install LLVM 7 and set variables for compilers to find it
brew install llvm@7
export PATH="/usr/local/opt/llvm@7/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm@7/lib"
export CPPFLAGS="-I/usr/local/opt/llvm@7/include"

# Install required packages
brew install pkg-config libffi cairo py3cairo

# Set variables for pkg-config to find libffi, which is needed for building
LIBFFI_PC_PATH=`locate libffi.pc | grep usr | head -n 1`
LIBFFI_PKGCONFIG_PATH=`dirname "$LIBFFI_PC_PATH"`
export PKG_CONFIG_PATH="$LIBFFI_PKGCONFIG_PATH"

pip install mplcairo
```

**Comment by anntzer** [comment]
Clarified the README in https://github.com/anntzer/mplcairo/commit/152d821d7fdb8dc4a73aa6f73e6c68e1aa4cde70; feel free to suggest edits and let me know if you find any other issues.
