### ISSUE TITLE
Will not compile on OX X 10.14

### ISSUE THREAD

**Issue by hyanwong** [anntzer/mplcairo#11]
when doing `pip3 install mplcairo` on the new version of OS X (Mojave) I get:

```
    src/_mplcairo.cpp:42:3: error: call to unavailable function 'visit': introduced in macOS 10.14
      std::visit([&](auto const& aa) -> void {
      ^~~~~~~~~~
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/variant:1524:26: note: candidate function [with _Visitor = (lambda at src/_mplcairo.cpp:42:14), _Vs = <const std::__1::variant<_cairo_antialias, bool> &>] has been explicitly made unavailable
    constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
                             ^
```

**Comment by anntzer** [comment]
From the error message, it looks like you are using Xcode's llvm?  You need to install a newer version with homebrew or anaconda, see https://github.com/anntzer/mplcairo#osx.

**Comment by hyanwong** [comment]
You are right. Thanks. I guess this can be closed then? Slightly annoying that the latest OS X version doesn't work out of the box (not your fault though!)

**Comment by anntzer** [comment]
Actually looking at this again perhaps it can be solved by changing the -mmacosx-version-min flag (twice) in https://github.com/anntzer/mplcairo/blob/master/setup.py#L151?  However I worry this will cause breakage on earlier OSX versions...

**Comment by hyanwong** [comment]
Hmm, thanks a lot for looking. I guess you want to avoid maintaining version-specific code here? It would be nice not to have to install a separate llvm for more recent OS versions. Let me know if you want me to try compiling with a different setup.py (lines 151 & 158) on the latest 10.14?

**Comment by hyanwong** [comment]
FWIW, I can confirm that this compiles on 10.14 if I set "-mmacosx-version-min=10.14" in both places, but will not if I set ""-mmacosx-version-min=10.13".

**Comment by anntzer** [comment]
I can live with version specific code if it helps, and here it definitely makes sense.
In practice I'll likely wait a bit until Azure CI update their images to 10.14 so that I can test (I don't have access to an OSX machine myself)...
If you are willing to help with this (that would be very appreciated): if you build a wheel on 10.14 (python setup.py bdist_wheel, perhaps followed with a call to https://pypi.org/project/delocate/ (not clear if it's actually needed)), can you try if that wheel works on a "naive" 10.14 machine (say, with no xcode, no custom llvm, no nothing?)  In other words, can I distribute a mplcairo-0.1-cp37-macosx_10_14_intel.whl with the expectation that it'll work on any 10.14 machine?

**Comment by hyanwong** [comment]
Apologies for the slow reply. I don't know much about wheel building etc, and I'm not sure how (or whether I want to) remove e.g. the command line developer tools I've installed. Perhaps better to wait until there are 10.14 images on Azure CI.

Also, it's not clear here if you want me to do this with the original "-mmacosx-version-min=10.9"?

**Comment by anntzer** [comment]
I decided to just push that patch in https://github.com/anntzer/mplcairo/commit/152d821d7fdb8dc4a73aa6f73e6c68e1aa4cde70.  Feel free to let me know if you find any additional issues.
